export const LOGIN_NAME = "LOGIN_NAME";
export const CHOOSENITEM = "CHOOSENITEM";
export const ADDSCORE = "ADDSCORE";
export const DELETESCORE = "DELETESCORE";
export const ADDFILTEREDDATA = "ADDFILTEREDDATA";
export const MODIFYFILTEREDDATA = "MODIFYFILTEREDDATA";
export const ANSWERS = "ANSWERS";
export const UPDATESCORE = "UPDATESCORE";
export const UPDATEANSWERS = "UPDATEANSWERS";

export const LOCALDATA = "LOCALDATA"
