export const LOGIN_NAME = "LOGIN_NAME";
export const ANSWERCHECK = "ANSWERCHECK"
export const CHOOSENITEM = "CHOOSENITEM"
export const ADDSCORE = "ADDSCORE"
export const DELETESCORE = "DELETESCORE"
export const ADDFILTEREDDATA = "ADDFILTEREDDATA"
export const MODIFYFILTEREDDATA = "MODIFYFILTEREDDATA"

